use crate::cli::TaskCommand;
use anyhow::Result;

pub(crate) use dw_task::open::{OpenWorkspaceArgs, open_workspace};

pub(crate) fn handle_task(command: TaskCommand) -> Result<()> {
    match command {
        TaskCommand::Status { root } => dw_task::open::status(root),
        TaskCommand::List {
            root,
            project,
            work_item,
            json,
        } => dw_task::open::list(root, project, work_item, json)?,
        TaskCommand::Current { json } => dw_task::open::current(json)?,
        TaskCommand::Open {
            workspace,
            project,
            work_item,
            positional_work_item,
            r#continue,
            repo,
            agent,
            json,
            root,
        } => dw_task::open::open_workspace(dw_task::open::OpenWorkspaceArgs {
            workspace,
            project,
            work_item,
            positional_work_item,
            r#continue,
            repo,
            agent,
            json,
            root,
        })?,
        TaskCommand::Start {
            work_item_id,
            root,
            project,
            task,
            type_name,
            only,
            slug,
            skip_ado,
            json,
            execute,
        } => dw_task::start::handle(dw_task::start::StartArgs {
            work_item_id,
            root,
            project,
            task,
            type_name,
            only,
            slug,
            skip_ado,
            json,
            execute,
        })?,
        TaskCommand::Preflight {
            workspace,
            ai_context_file,
            json,
        } => dw_task::validate::preflight(workspace, ai_context_file, json)?,
        TaskCommand::Sync {
            workspace,
            root,
            project,
            work_item,
            r#continue,
            positional_work_item,
            json,
        } => dw_task::lifecycle::sync(dw_task::lifecycle::SyncArgs {
            workspace,
            root,
            project,
            work_item,
            r#continue,
            positional_work_item,
            json,
        })?,
        TaskCommand::Rename {
            slug,
            workspace,
            root,
            project,
            work_item,
            r#continue,
            json,
            execute,
            positional_work_item,
        } => dw_task::lifecycle::rename(dw_task::lifecycle::RenameArgs {
            slug,
            workspace,
            root,
            project,
            work_item,
            r#continue,
            json,
            execute,
            positional_work_item,
        })?,
        TaskCommand::RepoLatest {
            workspace,
            r#continue,
            only,
            root,
            json,
        } => dw_task::repo::repo_latest(dw_task::repo::RepoLatestArgs {
            workspace,
            r#continue,
            only,
            root,
            json,
        })?,
        TaskCommand::Commit {
            workspace,
            r#continue,
            root,
            execute,
            message,
            json,
        } => dw_task::repo::commit(dw_task::repo::CommitArgs {
            workspace,
            r#continue,
            root,
            execute,
            message,
            json,
        })?,
        TaskCommand::AddWorkItem {
            work_item_ids,
            workspace,
            root,
            project,
            work_item,
            r#continue,
            positional_work_item,
            skip_ado,
            type_name,
            title,
            state,
            execute,
            json,
        } => dw_task::work_item::add(dw_task::work_item::AddWorkItemArgs {
            work_item_ids,
            workspace,
            root,
            project,
            work_item,
            r#continue,
            positional_work_item,
            skip_ado,
            type_name,
            title,
            state,
            execute,
            json,
        })?,
        TaskCommand::RemoveWorkItem {
            work_item_ids,
            workspace,
            root,
            project,
            work_item,
            r#continue,
            positional_work_item,
            execute,
            json,
        } => dw_task::work_item::remove(dw_task::work_item::RemoveWorkItemArgs {
            work_item_ids,
            workspace,
            root,
            project,
            work_item,
            r#continue,
            positional_work_item,
            execute,
            json,
        })?,
        TaskCommand::AddRepo {
            repo,
            workspace,
            root,
            execute,
            json,
        } => dw_task::repo::add_repo(dw_task::repo::AddRepoArgs {
            repo,
            workspace,
            root,
            execute,
            json,
        })?,
        TaskCommand::CreateChildTask {
            repo,
            title,
            workspace,
            root,
            project,
            work_item,
            r#continue,
            positional_work_item,
            json,
        } => dw_task::lifecycle::create_child_task(dw_task::lifecycle::CreateChildTaskArgs {
            repo,
            title,
            workspace,
            root,
            project,
            work_item,
            r#continue,
            positional_work_item,
            json,
        })?,
        TaskCommand::Finish {
            workspace,
            r#continue,
            root,
            execute,
            message,
            create_pr,
            ready,
            skip_verify,
            skip_ado,
            json,
        } => dw_task::finish::handle(dw_task::finish::FinishArgs {
            workspace,
            r#continue,
            root,
            execute,
            message,
            create_pr,
            ready,
            skip_verify,
            skip_ado,
            json,
        })?,
        TaskCommand::HandoffValidate { workspace, json } => {
            dw_task::validate::handoff_validate(workspace, json)?
        }
        TaskCommand::Teardown {
            workspace,
            root,
            project,
            work_item,
            r#continue,
            positional_work_item,
            execute,
            yes,
            json,
        } => dw_task::repo::teardown(dw_task::repo::TeardownArgs {
            workspace,
            root,
            project,
            work_item,
            r#continue,
            positional_work_item,
            execute,
            yes,
            json,
        })?,
        TaskCommand::Prune {
            root,
            project,
            work_item,
            execute,
            yes,
            no_sync,
            json,
        } => dw_task::prune::handle(dw_task::prune::PruneArgs {
            root,
            project,
            work_item,
            execute,
            yes,
            no_sync,
            json,
        })?,
    }

    Ok(())
}
