package spec

// commandCompletionText is completion-only presentation metadata. Command
// summaries remain independently suitable for help output.
var commandCompletionText = map[string]string{
	"version":                "Show the CLI version",
	"guide":                  "Getting started guide",
	"doctor":                 "Machine and configuration diagnostics",
	"init":                   "Initialize a DevWorkflow root",
	"refresh":                "Regenerate schemas and agent contexts",
	"tui":                    "Interactive dashboard",
	"agent":                  "Open/configure AI agents",
	"auth":                   "Azure DevOps login",
	"completion":             "Install/query shell completion",
	"config":                 "Read/modify configuration",
	"ado":                    "Azure DevOps commands",
	"db":                     "Read-only database access",
	"secret":                 "Local secrets",
	"upgrade":                "Update the binary",
	"work":                   "Workspace, repository, PR, and work-item lifecycle",
	"work.start":             "Create/prepare a workspace",
	"work.status":            "Workspace summary view",
	"work.list":              "List filterable workspaces",
	"work.current":           "Show the current workspace",
	"work.sync":              "Synchronize task.json with ADO",
	"work.preflight":         "Check blockers before development",
	"work.rename":            "Rename workspace and branch",
	"work.open":              "Open the workspace with an agent",
	"work.commit":            "Prepare or create commits",
	"work.finish":            "Commit, push, PR, and ADO state",
	"work.prune":             "Clean up finished workspaces",
	"work.teardown":          "Delete a workspace",
	"work.pr":                "Pull-request-based workspaces",
	"work.pr.start":          "Create/prepare a workspace from a PR",
	"work.item":              "Workspace work items",
	"work.item.doing":        "Move work items to their configured in-progress state",
	"work.item.add":          "Add work items to the workspace",
	"work.item.remove":       "Remove work items from the workspace",
	"work.repo":              "Workspace repositories",
	"work.repo.add":          "Add a repository to the workspace",
	"work.repo.latest":       "Update repositories",
	"work.handoff":           "Workspace handoffs",
	"work.handoff.validate":  "Validate workspace handoff",
	"work.task":              "ADO tasks linked to work",
	"work.task.child":        "Child tasks",
	"work.task.child.create": "Create an ADO child task",
	"auth.login":             "Interactive Azure DevOps login",
	"auth.status":            "Azure DevOps connection state",
	"auth.logout":            "Delete the local ADO session",
	"ado.assigned":           "Assigned work items",
	"ado.prs":                "Active pull requests",
	"ado.changelog":          "Changelog from PRs/git/work items",
	"ado.item":               "Work item operations",
	"ado.item.show":          "Work item details",
	"ado.state":              "Work item state operations",
	"ado.state.set":          "Change ADO state",
	"ado.context":            "Work item context",
	"ado.context.show":       "Detailed human-readable context",
	"ado.context.ai":         "Structured context for AI",
	"db.list":                "List configured databases safely",
	"db.collect":             "Discover workspace database connections",
	"db.schema":              "List tables and views",
	"db.describe":            "Describe a table",
	"db.query":               "Run a read-only query",
	"db.guard":               "Check a query without running it",
	"agent.context":          "Show agent context",
	"agent.open":             "Open an agent on a workspace",
	"agent.config":           "Show agent configuration",
	"agent.show":             "Agent configuration alias",
	"agent.default":          "Default agent operations",
	"agent.default.set":      "Set the default agent",
	"agent.doctor":           "Diagnose installed agents",
	"completion.show":        "Show installation commands",
	"completion.generate":    "Generate static completion",
	"completion.install":     "Show the dynamic shell snippet",
	"config.show":            "Show effective configuration",
	"config.root":            "Root configuration",
	"config.root.set":        "Set the DevWorkflow root",
	"config.color":           "Color configuration",
	"config.color.set":       "Set color mode",
	"config.doctor":          "Validate config files",
	"secret.list":            "List configured secret keys safely",
	"secret.set":             "Save a local secret",
	"secret.get":             "Check whether a secret exists",
	"secret.delete":          "Delete a local secret",
}

var optionCompletionText = map[string]string{
	"root": "DevWorkflow root to use", "project": "Configured project",
	"work-item": "Work item used to resolve the workspace", "workspace": "Existing task workspace",
	"repo": "Configured repository", "only": "Configured repository",
	"database": "Database connection declared in databases.json", "env": "Database environment alias",
	"json": "Deterministic JSON output", "execute": "Apply the action for real",
	"yes": "Confirm without interactive prompt", "dry-run": "Preview without writing",
	"no-save": "Do not save the default root", "save": "Save eligible collected connections securely",
	"fix": "Apply automatic fixes", "format": "Output format", "agent": "AI agent to launch",
	"max-rows": "Maximum number of rows", "sql": "Read-only SQL query", "message": "Explicit message",
	"title": "Explicit title", "task": "Child task to include", "slug": "Explicit slug",
	"value": "Secret value", "from-env": "Environment variable containing the secret",
	"state": "ADO state or local state depending on the command", "history": "ADO history message",
	"type": "Branch/workspace type", "profile": "Template profile", "check": "Check without updating",
	"rid": "Artifact runtime identifier", "continue": "Resume the recent workspace",
	"skip-ado": "Do not call Azure DevOps", "with-active-children": "Include active ADO children",
	"create-child-tasks": "Create ADO tasks per repository", "create-pr": "Create or verify ADO PRs",
	"ready": "Mark the PR as ready", "skip-verify": "Skip local validations",
	"force-with-lease": "Safely replace rewritten remote branches", "no-sync": "Skip ADO synchronization",
	"ai-context-file": "AI context file", "from-pr": "Read from pull requests",
	"from-git": "Read from git history", "group-by-parent": "Group by ADO parent",
	"table": "Table rendering", "ids-only": "Show IDs only", "git-to": "Ending git revision",
	"top": "Maximum number of items", "all": "Include final states", "summary": "Include the ADO summary",
	"comments": "Number of comments to include", "include-comments": "Include comments",
	"organization": "Azure DevOps organization", "help": "Show help",
}

var valueCompletionText = map[string]string{
	"project": "Configured project", "repo": "Repository", "only": "Repository",
	"database": "Database connection", "env": "Database environment", "workspace": "Task workspace",
	"work-item": "Local work item", "agent": "AI agent", "format": "Output format",
	"from-env": "Environment variable", "state": "ADO/workflow state", "max-rows": "Row limit",
	"type": "Branch/workspace type", "profile": "Profile",
}

var positionalCompletionText = map[string]string{
	"config.color.set": "Color mode", "agent.default.set": "Default AI agent",
	"completion.generate": "Target shell for static completion",
	"completion.install":  "Target shell for dynamic snippet",
	"secret.set":          "Secret key declared in databases.json",
	"secret.get":          "Secret key declared in databases.json",
	"secret.delete":       "Secret key declared in databases.json",
}
