package spec

// commandCompletionText is completion-only presentation metadata. Command
// summaries remain independently suitable for help output.
var commandCompletionText = map[string]string{
	"version": "Show the CLI version", "guide": "Getting started guide",
	"doctor": "Machine and configuration diagnostics", "init": "Initialize a DevWorkflow root",
	"refresh": "Regenerate schemas and agent contexts", "tui": "Interactive dashboard",
	"agent": "Open/configure AI agents", "completion": "Install/query shell completion",
	"config": "Read/modify configuration", "secret": "Local secrets", "upgrade": "Update the binary",
	"work": "External work and pull requests", "work.item": "Provider work items",
	"work.item.list": "List assigned work items", "work.item.show": "Show work item details",
	"work.item.doing": "Move work items to their in-progress state", "work.item.state": "Work item state operations",
	"work.item.state.set": "Change work item state", "work.item.child": "Child work items",
	"work.item.child.create": "Create a child work item", "work.pr": "Provider pull requests",
	"work.pr.list": "List active pull requests", "work.context": "Work item context",
	"work.context.show": "Detailed human-readable context", "work.context.ai": "Structured context for AI",
	"work.changelog": "Changelog from pull requests, git, or work items",
	"workspace":      "Local workspace and repository lifecycle", "workspace.status": "Workspace summary view",
	"workspace.list": "List filterable workspaces", "workspace.current": "Show the current workspace",
	"workspace.open": "Open the workspace with an agent", "workspace.start": "Create/prepare a workspace",
	"workspace.pr": "Pull-request-based workspaces", "workspace.pr.start": "Create/prepare a workspace from a pull request",
	"workspace.preflight": "Check blockers before development", "workspace.sync": "Synchronize task.json with provider work",
	"workspace.rename": "Rename workspace and branch", "workspace.repo": "Workspace repositories",
	"workspace.repo.add": "Add a repository to the workspace", "workspace.repo.latest": "Update repositories",
	"workspace.item": "Workspace work items", "workspace.item.add": "Add work items to the workspace",
	"workspace.item.remove": "Remove work items from the workspace", "workspace.commit": "Prepare or create commits",
	"workspace.finish": "Commit, push, pull request, and provider state", "workspace.handoff": "Workspace handoffs",
	"workspace.handoff.validate": "Validate workspace handoff", "workspace.teardown": "Delete a workspace",
	"workspace.prune": "Clean up finished workspaces",
	"data":            "Provider-neutral data access", "data.source": "Configured data sources",
	"data.source.list": "List configured data sources safely", "data.source.collect": "Discover workspace data connections",
	"data.guard": "Check a query without running it", "data.catalog": "List available data resources",
	"data.describe": "Describe a data resource", "data.query": "Run a read-only query",
	"provider": "Provider registry and authentication", "provider.list": "List registered providers",
	"provider.show": "Show provider details", "provider.capabilities": "List provider capabilities",
	"provider.auth": "Provider authentication", "provider.auth.login": "Connect a provider account",
	"provider.auth.status": "Show provider connection state", "provider.auth.logout": "Delete a local provider session",
	"agent.context": "Show agent context", "agent.open": "Open an agent on a workspace",
	"agent.config": "Show agent configuration", "agent.show": "Agent configuration alias",
	"agent.default": "Default agent operations", "agent.default.set": "Set the default agent",
	"agent.doctor": "Diagnose installed agents", "completion.show": "Show installation commands",
	"completion.generate": "Generate static completion", "completion.install": "Show the dynamic shell snippet",
	"config.show": "Show effective configuration", "config.root": "Root configuration",
	"config.root.set": "Set the DevWorkflow root", "config.color": "Color configuration",
	"config.color.set": "Set color mode", "config.doctor": "Validate config files",
	"secret.list": "List configured secret keys safely", "secret.set": "Save a local secret",
	"secret.get": "Check whether a secret exists", "secret.delete": "Delete a local secret",
}

var optionCompletionText = map[string]string{
	"root": "DevWorkflow root to use", "project": "Configured project", "provider": "Configured provider",
	"work-item": "Work item used to resolve the workspace", "workspace": "Existing task workspace",
	"repo": "Configured repository", "only": "Configured repository",
	"source": "Configured data source", "env": "Data source environment alias",
	"json": "Deterministic JSON output", "execute": "Apply the action for real",
	"yes": "Confirm without interactive prompt", "dry-run": "Preview without writing",
	"no-save": "Do not save the default root", "save": "Save eligible collected connections securely",
	"fix": "Apply automatic fixes", "format": "Output format", "agent": "AI agent to launch",
	"max-rows": "Maximum number of rows", "query": "Read-only query", "message": "Explicit message",
	"title": "Explicit title", "task": "Child task to include", "slug": "Explicit slug",
	"value": "Secret value", "from-env": "Environment variable containing the secret",
	"state": "Provider work state or local state depending on the command", "history": "Work item history message",
	"type": "Branch/workspace type", "profile": "Template profile", "check": "Check without updating",
	"rid": "Artifact runtime identifier", "continue": "Resume the recent workspace",
	"skip-provider": "Do not call the work provider", "with-active-children": "Include active children",
	"create-child-tasks": "Create provider tasks per repository", "create-pr": "Create or verify provider pull requests",
	"ready": "Mark the pull request as ready", "skip-verify": "Skip local validations",
	"force-with-lease": "Safely replace rewritten remote branches", "no-sync": "Skip provider synchronization",
	"ai-context-file": "AI context file", "from-pr": "Read from pull requests",
	"from-git": "Read from git history", "group-by-parent": "Group by work item parent",
	"table": "Table rendering", "ids-only": "Show IDs only", "git-to": "Ending git revision",
	"top": "Maximum number of items", "all": "Include final states", "summary": "Include the work summary",
	"comments": "Number of comments to include", "include-comments": "Include comments",
	"organization": "Provider organization or account", "help": "Show help",
}

var valueCompletionText = map[string]string{
	"project": "Configured project", "provider": "Provider", "repo": "Repository", "only": "Repository",
	"source": "Data source", "env": "Data source environment", "workspace": "Task workspace",
	"work-item": "Work item", "agent": "AI agent", "format": "Output format",
	"from-env": "Environment variable", "state": "Work item or workflow state", "max-rows": "Row limit",
	"type": "Branch/workspace type", "profile": "Profile",
}

var positionalCompletionText = map[string]string{
	"config.color.set": "Color mode", "agent.default.set": "Default AI agent",
	"completion.generate": "Target shell for static completion", "completion.install": "Target shell for dynamic snippet",
	"secret.set": "Configured secret key", "secret.get": "Configured secret key", "secret.delete": "Configured secret key",
	"provider.show": "Registered provider", "provider.capabilities": "Registered provider",
	"provider.auth.login": "Registered provider", "provider.auth.status": "Registered provider",
	"provider.auth.logout": "Registered provider",
}
