package spec

func workGrammar(b *builder) *Command {
	item := b.command("item", "work.item", "Inspect and manage provider work items.", nil,
		b.command("list", "work.item.list", "List work items assigned to the current user.", []Argument{
			b.option("work.item.list", "root", String, "DevWorkflow root to use."),
			completion(b.option("work.item.list", "project", String, "Configured project to query; opens an interactive picker when omitted."), CompleteProject),
			providerOption(b, "work.item.list"),
			defaultInt(b.option("work.item.list", "top", Int, "Maximum number of work items to load."), 20),
			b.option("work.item.list", "all", Bool, "Also include work items in a final state."),
			b.option("work.item.list", "group-by-parent", Bool, "Group work items by parent."),
			b.option("work.item.list", "json", Bool, "Emit the deterministic JSON response."),
		}),
		b.command("show", "work.item.show", "Show a readable summary of work items.", []Argument{
			b.positional("work.item.show", "id", "ID", String, true, "Work item ID, or comma-separated list."),
			b.option("work.item.show", "root", String, "DevWorkflow root to use."),
			completion(b.option("work.item.show", "project", String, "Configured project to use."), CompleteProject),
			providerOption(b, "work.item.show"),
			b.option("work.item.show", "json", Bool, "Emit the deterministic JSON response."),
		}),
		b.command("doing", "work.item.doing", "Move work items to their configured in-progress state.", []Argument{
			b.positional("work.item.doing", "id", "ID", String, true, "Work item ID, or comma-separated list."),
			b.option("work.item.doing", "root", String, "DevWorkflow root to use."),
			completion(b.option("work.item.doing", "project", String, "Configured project to use."), CompleteProject),
			providerOption(b, "work.item.doing"),
			b.option("work.item.doing", "yes", Bool, "Confirm the work item state changes."),
			b.option("work.item.doing", "json", Bool, "Emit the deterministic report JSON; requires --yes."),
		}),
		b.command("state", "work.item.state", "Manage work item state.", nil,
			b.command("set", "work.item.state.set", "Change the state of one or more work items.", []Argument{
				b.positional("work.item.state.set", "id", "ID", String, true, "Work item ID, or comma-separated list."),
				b.option("work.item.state.set", "root", String, "DevWorkflow root to use."),
				completion(b.option("work.item.state.set", "project", String, "Configured project to use."), CompleteProject),
				providerOption(b, "work.item.state.set"),
				mandatory(completion(b.option("work.item.state.set", "state", String, "Exact new work item state to apply."), CompleteWorkState)),
				b.option("work.item.state.set", "history", String, "History message; default: dw work item state set."),
				b.option("work.item.state.set", "yes", Bool, "Confirm the destructive state change."),
				b.option("work.item.state.set", "json", Bool, "Emit the deterministic JSON response; requires --yes."),
			}),
		),
		b.command("child", "work.item.child", "Manage child work items.", nil,
			b.command("create", "work.item.child.create", "Create a child work item and add it to the repository handoff.", []Argument{
				mandatory(completion(b.option("work.item.child.create", "repo", String, "Workspace repository that will carry the task handoff."), CompleteRepository)),
				mandatory(b.option("work.item.child.create", "title", String, "Title of the child work item to create.")),
				completion(b.option("work.item.child.create", "workspace", String, "Workspace path to modify."), CompleteWorkspace),
				b.option("work.item.child.create", "root", String, "DevWorkflow root to use."),
				completion(b.option("work.item.child.create", "project", String, "Configured project used to resolve the workspace."), CompleteProject),
				providerOption(b, "work.item.child.create"),
				completion(b.option("work.item.child.create", "work-item", String, "Work item used to resolve the workspace."), CompleteWorkItem),
				b.option("work.item.child.create", "continue", Bool, "Resume the most recent workspace."),
				b.option("work.item.child.create", "json", Bool, "Emit the deterministic result JSON."),
				b.positional("work.item.child.create", "positional_work_item", "WORK_ITEM", String, false, "Positional work item alias used to resolve the workspace."),
			}),
		),
	)
	pr := b.command("pr", "work.pr", "Inspect provider pull requests.", nil,
		b.command("list", "work.pr.list", "List active pull requests from configured repositories.", []Argument{
			b.option("work.pr.list", "root", String, "DevWorkflow root to use."),
			mandatory(completion(b.option("work.pr.list", "project", String, "Configured project to query."), CompleteProject)),
			providerOption(b, "work.pr.list"),
			completion(b.option("work.pr.list", "repo", String, "Local or provider repository to query; repeat with commas."), CompleteRepository),
			b.option("work.pr.list", "json", Bool, "Emit the deterministic JSON response."),
		}),
	)
	context := b.command("context", "work.context", "Build human-readable or AI-ready work item context.", nil,
		b.command("show", "work.context.show", "Show detailed context in a human-readable format.", []Argument{
			b.positional("work.context.show", "id", "ID", String, true, "Work item ID, or comma-separated list."),
			b.option("work.context.show", "root", String, "DevWorkflow root to use."),
			completion(b.option("work.context.show", "project", String, "Configured project to use."), CompleteProject),
			providerOption(b, "work.context.show"),
			b.option("work.context.show", "summary", Bool, "Limit context to essential fields."),
			defaultInt(b.option("work.context.show", "comments", Int, "Maximum number of comments to show; 0 for none."), 200),
			b.option("work.context.show", "json", Bool, "Emit the deterministic JSON response."),
		}),
		b.command("ai", "work.context.ai", "Emit structured, deterministic AI context.", []Argument{
			b.positional("work.context.ai", "id", "ID", String, true, "Work item ID, or comma-separated list."),
			b.option("work.context.ai", "root", String, "DevWorkflow root to use."),
			providerOption(b, "work.context.ai"),
			b.option("work.context.ai", "organization", String, "Explicit provider organization or account."),
			completion(b.option("work.context.ai", "project", String, "Configured or explicit provider project."), CompleteProject),
			b.option("work.context.ai", "summary", Bool, "Limit the contract to essential fields."),
			defaultInt(b.option("work.context.ai", "comments", Int, "Maximum number of comments to include."), 200),
			b.option("work.context.ai", "include-comments", Bool, "Include comments in the AI context."),
		}),
	)
	changelog := b.command("changelog", "work.changelog", "Build a changelog from pull requests, a git range, or work items.", []Argument{
		b.positional("work.changelog", "ids", "IDS", String, true, "Work item IDs, pull requests, or git range depending on the selected mode."),
		b.option("work.changelog", "root", String, "DevWorkflow root to use."),
		completion(b.option("work.changelog", "project", String, "Configured project to use."), CompleteProject),
		providerOption(b, "work.changelog"),
		conflict(b.option("work.changelog", "from-pr", Bool, "Interpret IDs as provider pull requests."), "from_git"),
		conflict(b.option("work.changelog", "from-git", Bool, "Extract work items from git commits."), "from_pr"),
		completion(b.option("work.changelog", "repo", String, "Configured repository key/name or local path; omit to scan every configured repository."), CompleteRepository),
		b.option("work.changelog", "group-by-parent", Bool, "Group the changelog by work item parent."),
		completion(choices(b.option("work.changelog", "format", String, "Output format."), "raw", "markdown", "html"), CompleteFormat, "raw", "markdown", "html"),
		require(b.option("work.changelog", "table", Bool, "Render the markdown/html changelog as a table."), "format"),
		b.option("work.changelog", "ids-only", Bool, "Show only resolved IDs, separated by spaces."),
		require(b.option("work.changelog", "git-to", String, "Ending revision for the git range."), "from_git"),
	})
	return b.command("work", "work", "Inspect and manage external work through configured providers.", nil, item, pr, context, changelog)
}
